services:
  - type: web
    name: agent-zero
    env: docker
    plan: free
    dockerfilePath: ./DockerfileRender
    region: frankfurt
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "80"
      - key: DEFAULT_USER_TIMEZONE
        value: Europe/Paris
      - key: DEFAULT_USER_UTC_OFFSET_MINUTES
        value: "60"
